name: bbh-alphastats
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  # conda-forge packages (fast + compiled)
  - scipy>=1.9,<2.0
  - natsort>=8.4,<9
  - openpyxl>=3.1.5,<4
  - nbformat>=5.10.4,<6
  - notebook>=7.3.2,<8
  - ipykernel>=6.29.5,<7
  - goatools>=1.4.12,<2
  - upsetplot>=0.9,<0.10
  - matplotlib-venn>=1.1.1,<2
  # optional but often useful
  - pandas
  - numpy
  - jupyterlab
  - pip:
      - alphastats>=0.6.9
      - pimms-learn>=0.5.0,<0.6.0
      - gprofiler-official>=1.0.0,<2.0.0
      - gprofiler>=1.2.2,<2.0.0
